name: Build and Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Initialize submodules
        run: |
          git submodule update --init --recursive

      - name: Set environment variables
        run: |
          echo "RELEASE_TAG=build-$(date +'%Y%m%d')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "LATEST_COMMIT_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BUILD=true" >> $GITHUB_ENV

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get remove llvm*
          sudo apt-get install -y \
            libzimg-dev \
            meson \
            libxxhash-dev \
            nasm \
            libfftw3-dev \
            gcc g++ \
            make \
            wget \
            unzip

      - name: Install LLVM 20
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          sudo apt-get update
          sudo apt-get install -y llvm-20 llvm-20-dev clang-20 lld-20 lldb-20
          sudo ln -s /usr/bin/llvm-config-20 /usr/bin/llvm-config

      - name: Run build script
        run: bash build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plugins
          path: out/*

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "Build ${{ env.LATEST_COMMIT_SHORT }}"
          body: |
            Automated build triggered by changes to repository

            [View changes](https://github.com/${{ github.repository }}/commit/${{ env.LATEST_COMMIT_SHORT }})
          files: out/*
          token: ${{ secrets.GITHUB_TOKEN }}
